# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default  
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci

development:
  <<: *default
  database: salon-development
  username: root
  password:

test:
  <<: *default
  host: 127.0.0.1
  database: salon-test
  username: root
  password:

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
